title: Whirlpool Editor
theme: jekyll-theme-cayman
show_downloads: true
description: Simple, open-source Java editor
github:
  zip_url: https://github.com/TerabyteTB/TextEditor/archive/v0.0.1.zip
  tar_url: https://github.com/TerabyteTB/TextEditor/archive/v0.0.1.tar.gz
  exe_url: https://www.github.com/TerabyteTB/WhirlpoolEditor/releases/download/v0.0.1.1/editor.exe
