version: 2.1

orbs:
  maven: circleci/maven@1.1
  
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    

workflows:
  maven_test:
    jobs:
      - maven/test:
          app_src_directory: 'Editor/'
