version: 2.1

orbs:
  maven: circleci/maven@1.1
  codecov: codecov/codecov@1.1.3
  coveralls: coveralls/coveralls@1.0.4
  
jobs:
  build:
    docker: 
      - image: circleci/openjdk:8-jdk-stretch
    steps: 
      - checkout
      - run:
          name: Run tests
          command: mvn -f Editor/ clean install; mvn -f Editor/ cobertura:cobertura
      - run:
          name: Upload to Coveralls
          command: mvn -f Editor/ clean test; mvn -f Editor/ cobertura:cobertura -Dcobertura.report.format=xml coveralls:report -Dproject.build.sourceEncoding=UTF-8; cat Editor/target/site/cobertura/coverage.xml
      - codecov/upload:
          file: Editor/target/site/cobertura/coverage.xml
      
workflows:
  test:
    jobs:
      - build
