version: 2.1

orbs:
  maven: circleci/maven@1.1
  
jobs:
  build:
    docker:
      - image: circleci/openjdk:15-jdk-stretch
    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn -f Editor/ clean test

workflows:
  test:
    jobs:
      - build
