version: 2.1

orbs:
  maven: circleci/maven@1.1
    
workflows:
  build:
    jobs:
      - maven/test:
          docker:
              - image: circleci/openjdk:8-jdk-stretch
          app_src_directory: 'Editor/'
